name: flutter_book_of_shaders
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.0-444.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  shaders:
    - shaders/src/1-getting-started/hello-world.glsl
    - shaders/src/1-getting-started/uniforms-1.glsl
    - shaders/src/1-getting-started/uniforms-2.glsl
    - shaders/src/2-algorithmic-drawing/shaping-functions-1.glsl
    - shaders/src/2-algorithmic-drawing/shaping-functions-2.glsl
    - shaders/src/2-algorithmic-drawing/shaping-functions-3.glsl
    - shaders/src/2-algorithmic-drawing/shaping-functions-4.glsl
    - shaders/src/misc/creation.glsl
    - shaders/src/misc/simple.glsl
    - shaders/src/misc/simplex-3d.glsl
    - shaders/src/misc/uv-sampler.glsl
